#!/usr/bin/env bash
set -u

# ElysianNodes NRO controller, managed from GitHub.
# Existing layout remains compatible:
#   stock emulator -> ~/microemu/
#   legacy game    -> ~/game.jar
# New uploads:
#   ~/emulators/*.jar
#   ~/games/*.jar
# New per-pair state:
#   ~/nro-data/profiles/<game>/<emulator>/.microemulator/
#
# reset-state deletes ONLY the selected pair's .microemulator state.

ROOT="${NRO_ROOT:-${HOME:-/home/container}}"
DATA="${NRO_DATA:-$ROOT/nro-data}"

GAMES_DIR="$ROOT/games"
EMULATORS_DIR="$ROOT/emulators"
PROFILES_DIR="$DATA/profiles"
SELECTION_FILE="$DATA/current-selection.env"

# Runtime-selected values are resolved by choose_runtime().
EMU_SELECTOR=""
GAME_SELECTOR=""
EMU_NAME=""
GAME_NAME=""
EMU_JAR=""
GAME=""
EMU_HOME=""
STATE=""
JAD=""
CP=""
MIDLET_CLASS=""

VNC_ROOT="$ROOT/vnc"
VNC_ORIG="$VNC_ROOT/usr/bin/Xtigervnc"
VNC_BIN="$VNC_ROOT/usr/bin/Xtigervnc-elysian"
XKBCOMP="$VNC_ROOT/usr/bin/xkbcomp"
XKBDIR="$VNC_ROOT/usr/share/X11/xkb"
VNC_PASS="$ROOT/.vnc/passwd"
VNC_LIB="$VNC_ROOT/usr/lib/x86_64-linux-gnu:$VNC_ROOT/lib/x86_64-linux-gnu:$VNC_ROOT/usr/lib"

DISPLAY_NUM=":1"
VNC_PORT="${VNC_PORT:-2496}"
VNC_GEOMETRY="640x480"

NRO_SERVER_PORT="${NRO_SERVER_PORT:-14445}"
NETWORK_WATCHDOG="${NETWORK_WATCHDOG:-0}"
HEALTH_GRACE="${HEALTH_GRACE:-120}"
HEALTH_INTERVAL="${HEALTH_INTERVAL:-30}"
HEALTH_FAILS="${HEALTH_FAILS:-4}"

# Conservative freeze detector: if Java is alive but the game log has not
# changed for a long time, restart only the game process.
STALL_WATCHDOG="${STALL_WATCHDOG:-1}"
STALL_TIMEOUT="${STALL_TIMEOUT:-300}"

# Detect the specific NRO render/update loop (nro.cr.run). The JVM/AWT can
# remain alive after that thread dies, leaving a blank MicroEmulator window.
LOOP_WATCHDOG="${LOOP_WATCHDOG:-1}"
LOOP_CHECK_INTERVAL="${LOOP_CHECK_INTERVAL:-60}"
LOOP_FAILS="${LOOP_FAILS:-2}"
LOOP_THREAD_PATTERN="${LOOP_THREAD_PATTERN:-}"

JAVA_XMS="${JAVA_XMS:-32m}"
JAVA_XMX="${JAVA_XMX:-192m}"

VNC_PID="$ROOT/vnc.pid"
SUP_PID="$ROOT/game-supervisor.pid"
GAME_PID="$ROOT/game.pid"
VNC_LOG="$DATA/logs/vnc.log"
GAME_LOG="$DATA/logs/game.log"
SUP_LOG="$DATA/logs/supervisor.log"

SELF="$(readlink -f "$0" 2>/dev/null || printf '%s' "$0")"

pid_alive() {
  local f="$1" p
  [[ -s "$f" ]] || return 1
  p="$(cat "$f" 2>/dev/null || true)"
  [[ -n "$p" ]] && kill -0 "$p" 2>/dev/null
}

find_vnc_pid() {
  local p cmd
  [[ -s "$VNC_PID" ]] || return 1
  p="$(cat "$VNC_PID" 2>/dev/null || true)"
  [[ -n "$p" ]] || return 1
  kill -0 "$p" 2>/dev/null || return 1

  # Avoid treating a reused/stale PID as our VNC process.
  cmd="$(tr '\0' ' ' < "/proc/$p/cmdline" 2>/dev/null || true)"
  [[ "$cmd" == *"Xtigervnc"* ]] || return 1

  printf '%s\n' "$p"
}

find_game_pid() {
  if pid_alive "$GAME_PID"; then cat "$GAME_PID"; return 0; fi
  return 1
}

port_listening() {
  ss -ltn 2>/dev/null | awk '{print $4}' | grep -Eq "(^|:)$VNC_PORT$"
}

game_connected() {
  ss -Htn state established 2>/dev/null | awk -v p=":$NRO_SERVER_PORT" '$5 ~ (p "$") {ok=1} END {exit !ok}'
}

trim_log() {
  local f="$1" tmp="${1}.tmp.$"
  [[ -f "$f" ]] || return 0
  tail -n 160 "$f" > "$tmp" 2>/dev/null || true
  mv -f "$tmp" "$f" 2>/dev/null || true
}

file_age_seconds() {
  local f="$1" now mtime
  [[ -e "$f" ]] || return 1
  now="$(date +%s)"
  mtime="$(stat -c %Y "$f" 2>/dev/null || true)"
  [[ -n "$mtime" ]] || return 1
  printf '%s\n' "$(( now - mtime ))"
}

safe_key() {
  printf '%s' "$1" | sed 's/\.jar$//I; s/[^A-Za-z0-9._-]/_/g'
}

load_selection() {
  EMU_SELECTOR=""
  GAME_SELECTOR=""

  if [[ -s "$SELECTION_FILE" ]]; then
    # Generated by save_selection() using shell-escaped values.
    # shellcheck disable=SC1090
    source "$SELECTION_FILE"
  fi

  [[ -n "$EMU_SELECTOR" && -n "$GAME_SELECTOR" ]]
}

save_selection() {
  mkdir -p "$DATA"
  {
    printf 'EMU_SELECTOR=%q\n' "$EMU_SELECTOR"
    printf 'GAME_SELECTOR=%q\n' "$GAME_SELECTOR"
  } > "$SELECTION_FILE"
}

resolve_emulator() {
  local sel="$1" candidate="" dir=""

  EMU_SELECTOR="$sel"

  if [[ "$sel" == "stock" ]]; then
    [[ -s "$ROOT/microemu/microemulator.jar" ]] || return 1
    EMU_NAME="stock"
    EMU_JAR="$ROOT/microemu/microemulator.jar"
    CP="$ROOT/microemu/microemulator.jar:$ROOT/microemu/lib/*:$ROOT/microemu/devices/*"
    return 0
  fi

  if [[ -s "$EMULATORS_DIR/$sel" ]]; then
    candidate="$EMULATORS_DIR/$sel"
  elif [[ -s "$EMULATORS_DIR/$sel.jar" ]]; then
    candidate="$EMULATORS_DIR/$sel.jar"
  else
    return 1
  fi

  if command -v unzip >/dev/null 2>&1; then
    unzip -l "$candidate" org/microemu/app/Main.class 2>/dev/null |
      grep -q 'org/microemu/app/Main.class' || {
        echo "[ERROR] Emulator is not MicroEmulator-compatible: $candidate" >&2
        return 1
      }
  fi

  EMU_JAR="$candidate"
  EMU_NAME="$(basename "$candidate")"
  EMU_NAME="${EMU_NAME%.jar}"
  dir="$(dirname "$candidate")"
  CP="$candidate:$dir/lib/*:$dir/devices/*"
}

resolve_game() {
  local sel="$1"

  GAME_SELECTOR="$sel"

  if [[ "$sel" == "game" || "$sel" == "game.jar" ]]; then
    [[ -s "$ROOT/game.jar" ]] || return 1
    GAME="$ROOT/game.jar"
  elif [[ -s "$GAMES_DIR/$sel" ]]; then
    GAME="$GAMES_DIR/$sel"
  elif [[ -s "$GAMES_DIR/$sel.jar" ]]; then
    GAME="$GAMES_DIR/$sel.jar"
  else
    return 1
  fi

  GAME_NAME="$(basename "$GAME")"
}

detect_midlet() {
  local unfolded line cls

  command -v unzip >/dev/null 2>&1 || {
    echo "[ERROR] unzip is required to inspect the game JAR" >&2
    return 1
  }

  unfolded="$(
    unzip -p "$GAME" META-INF/MANIFEST.MF 2>/dev/null |
      tr -d '\r' |
      awk '
        /^[ ]/ {
          sub(/^ /, "")
          line = line $0
          next
        }
        {
          if (line != "") print line
          line = $0
        }
        END {
          if (line != "") print line
        }
      '
  )"

  line="$(printf '%s\n' "$unfolded" | grep -m1 '^MIDlet-1[[:space:]]*:')"
  [[ -n "$line" ]] || {
    echo "[ERROR] MIDlet-1 not found in $GAME" >&2
    return 1
  }

  cls="$(printf '%s\n' "$line" | awk -F',' '{v=$NF; gsub(/^[ \t]+|[ \t]+$/, "", v); print v}')"
  [[ -n "$cls" ]] || return 1
  MIDLET_CLASS="$cls"

  # The old watchdog knows this thread only for the stock NRO client.
  # Modded clients can rename/obfuscate it, so never restart them from an
  # unverified symbol. LOOP_THREAD_PATTERN can still be provided explicitly.
  if [[ -z "$LOOP_THREAD_PATTERN" ]]; then
    if [[ "$MIDLET_CLASS" == "nro.GameMidlet" ]]; then
      LOOP_THREAD_PATTERN='nro\.cr\.run\('
    else
      LOOP_WATCHDOG=0
      STALL_WATCHDOG=0
    fi
  fi
}

select_runtime() {
  local emu_sel="$1" game_sel="$2" game_key emu_key

  resolve_emulator "$emu_sel" || {
    echo "[ERROR] Emulator not found: $emu_sel" >&2
    echo "        Upload emulator JARs to: $EMULATORS_DIR" >&2
    return 1
  }

  resolve_game "$game_sel" || {
    echo "[ERROR] Game not found: $game_sel" >&2
    echo "        Upload game JARs to: $GAMES_DIR" >&2
    return 1
  }

  detect_midlet || return 1

  if [[ "$EMU_NAME" == "stock" && "$GAME" == "$ROOT/game.jar" ]]; then
    # Preserve the existing Elysian login/RMS path exactly.
    EMU_HOME="$ROOT/microemu-home"
  else
    game_key="$(safe_key "$GAME_NAME")"
    emu_key="$(safe_key "$EMU_NAME")"
    EMU_HOME="$PROFILES_DIR/$game_key/$emu_key"
  fi

  STATE="$EMU_HOME/.microemulator"
  JAD="$EMU_HOME/game-manifest.jad"
}

choose_runtime() {
  local emu_arg="${1:-}" game_arg="${2:-}"

  if [[ -n "$emu_arg" || -n "$game_arg" ]]; then
    if [[ -z "$emu_arg" || -z "$game_arg" ]]; then
      echo "[ERROR] Give both emulator and game" >&2
      echo "        Example: restart MICRO_NST AUTO50_X1" >&2
      return 1
    fi
    select_runtime "$emu_arg" "$game_arg" || return 1
    save_selection
    return 0
  fi

  if load_selection; then
    select_runtime "$EMU_SELECTOR" "$GAME_SELECTOR"
    return $?
  fi

  # Existing Elysian installs keep working without migration.
  if [[ -s "$ROOT/microemu/microemulator.jar" && -s "$ROOT/game.jar" ]]; then
    select_runtime "stock" "game.jar" || return 1
    save_selection
    return 0
  fi

  echo "[ERROR] No runtime selected" >&2
  echo "        Run 'list', then 'restart <emulator> <game>'" >&2
  return 1
}

list_runtime() {
  local f name found=0

  mkdir -p "$GAMES_DIR" "$EMULATORS_DIR" "$PROFILES_DIR"

  echo "================ AVAILABLE ================="
  echo "Emulators:"

  if [[ -s "$ROOT/microemu/microemulator.jar" ]]; then
    printf '  %-22s %s\n' "stock" "$ROOT/microemu/microemulator.jar"
    found=1
  fi

  for f in "$EMULATORS_DIR"/*.jar; do
    [[ -f "$f" ]] || continue
    name="$(basename "$f")"
    printf '  %-22s %s\n' "${name%.jar}" "$f"
    found=1
  done
  [[ "$found" -eq 1 ]] || echo "  (none)"

  echo
  echo "Games:"
  found=0

  if [[ -s "$ROOT/game.jar" ]]; then
    printf '  %-26s %s (legacy)\n' "game.jar" "$ROOT/game.jar"
    found=1
  fi

  for f in "$GAMES_DIR"/*.jar; do
    [[ -f "$f" ]] || continue
    name="$(basename "$f")"
    printf '  %-26s %s\n' "$name" "$f"
    found=1
  done
  [[ "$found" -eq 1 ]] || echo "  (none)"

  echo
  if load_selection; then
    echo "Current selection:"
    echo "  emulator: $EMU_SELECTOR"
    echo "  game:     $GAME_SELECTOR"
  else
    echo "Current selection: legacy default (stock + game.jar)"
  fi
  echo "============================================"
}

game_loop_thread_alive() {
  local pid="$1" dump=""
  [[ "$LOOP_WATCHDOG" == "1" ]] || return 0

  if command -v jcmd >/dev/null 2>&1; then
    dump="$(timeout 8s jcmd "$pid" Thread.print 2>/dev/null || true)"
  elif command -v jstack >/dev/null 2>&1; then
    dump="$(timeout 8s jstack "$pid" 2>/dev/null || true)"
  else
    # No thread-dump tool: do not kill based on an unverifiable condition.
    return 0
  fi

  [[ -n "$dump" ]] || return 0
  printf '%s\n' "$dump" | grep -Eq "$LOOP_THREAD_PATTERN"
}

prepare() {
  mkdir -p "$DATA" "$DATA/logs" "$EMU_HOME" "$STATE" "$ROOT/.vnc" /tmp/xxx

  [[ -s "$GAME" ]] || { echo "[ERROR] Missing game: $GAME"; return 1; }
  [[ -s "$EMU_JAR" ]] || { echo "[ERROR] Missing emulator: $EMU_JAR"; return 1; }
  [[ -s "$VNC_PASS" ]] || { echo "[ERROR] Missing VNC password file: $VNC_PASS"; return 1; }

  if command -v unzip >/dev/null 2>&1; then
    unzip -p "$GAME" META-INF/MANIFEST.MF 2>/dev/null | tr -d '\r' > "$JAD.tmp" || true
    if [[ -s "$JAD.tmp" ]]; then mv -f "$JAD.tmp" "$JAD"; else rm -f "$JAD.tmp"; fi
  fi

  if [[ ! -e "$STATE/suite-null" && ! -L "$STATE/suite-null" ]]; then
    mkdir -p "$STATE/suite-null"
  fi

  # Xtigervnc was built to execute /usr/bin/xkbcomp. We cannot install
  # packages system-wide on Elysian, so patch that fixed-length path to /tmp/xxx
  # and place a wrapper there. The wrapper injects the portable XKB include
  # root, which fixes "Can't find file evdev for keycodes include".
  rm -f /tmp/xxx/xkbcomp
  cat > /tmp/xxx/xkbcomp <<EOF
#!/bin/sh
exec "$XKBCOMP" -I"$XKBDIR" "\$@"
EOF
  chmod +x /tmp/xxx/xkbcomp

  # Rebuild the patched binary on every start so a script update is never
  # masked by a stale cached Xtigervnc-elysian binary.
  cp "$VNC_ORIG" "$VNC_BIN"
  sed -i 's#/usr/bin#/tmp/xxx#g' "$VNC_BIN"
  chmod +x "$VNC_BIN"
}

start_vnc() {
  local p
  p="$(find_vnc_pid || true)"
  if [[ -n "$p" ]] && port_listening; then
    echo "[VNC] already ON (pid $p, port $VNC_PORT)"
    return 0
  fi

  # Stale PID file or half-dead X server: do not skip startup.
  if [[ -s "$VNC_PID" ]]; then
    echo "[VNC] stale/dead pidfile detected; starting a fresh X/VNC server"
    rm -f "$VNC_PID"
  fi

  : > "$VNC_LOG"
  echo "[VNC] starting with portable XKB root: $XKBDIR"
  LD_LIBRARY_PATH="$VNC_LIB:${LD_LIBRARY_PATH:-}" \
  nohup "$VNC_BIN" "$DISPLAY_NUM" \
    -geometry "$VNC_GEOMETRY" \
    -depth 24 \
    -rfbport "$VNC_PORT" \
    -localhost no \
    -SecurityTypes VncAuth \
    -rfbauth "$VNC_PASS" \
    -xkbdir "$XKBDIR" \
    >"$VNC_LOG" 2>&1 &

  echo $! > "$VNC_PID"
  local i
  for i in 1 2 3 4 5 6; do
    sleep 0.5
    if pid_alive "$VNC_PID" && port_listening; then break; fi
  done

  if pid_alive "$VNC_PID" && port_listening; then
    echo "[VNC] ON (pid $(cat "$VNC_PID"), port $VNC_PORT)"
  else
    echo "[VNC] failed to start"
    tail -n 100 "$VNC_LOG" 2>/dev/null || true
    return 1
  fi
}

game_loop() {
  trap 'if [[ -s "'"$GAME_PID"'" ]]; then p="$(cat "'"$GAME_PID"'" 2>/dev/null)"; [[ -n "$p" ]] && kill "$p" 2>/dev/null || true; fi; rm -f "'"$GAME_PID"'"; exit 0' TERM INT

  export DISPLAY="$DISPLAY_NUM"
  export LD_LIBRARY_PATH="$VNC_LIB:${LD_LIBRARY_PATH:-}"

  while true; do
    : > "$GAME_LOG"
    java       -Xms"$JAVA_XMS"       -Xmx"$JAVA_XMX"       -XX:+UseSerialGC       -Duser.home="$EMU_HOME"       -Dswing.defaultlaf=javax.swing.plaf.nimbus.NimbusLookAndFeel       -cp "$CP"       org.microemu.app.Main       --rms file       --resizableDevice 320 240       --appclasspath "$GAME"       --propertiesjad "$JAD"       --quit       "$MIDLET_CLASS"       >>"$GAME_LOG" 2>&1 &

    local child=$!
    echo "$child" > "$GAME_PID"
    printf '[%s] watchdog started game pid=%s\n' "$(date '+%F %T')" "$child" >> "$SUP_LOG"

    local started failures elapsed loop_failures last_loop_check now loop_ok log_age
    started="$(date +%s)"
    failures=0
    loop_failures=0
    last_loop_check=0
    loop_ok=0
    while kill -0 "$child" 2>/dev/null; do
      sleep "$HEALTH_INTERVAL"
      kill -0 "$child" 2>/dev/null || break

      # The MicroEmulator/AWT process can survive while NRO's actual
      # update/render thread dies. Check that specific loop independently
      # of network traffic and framebuffer/VNC state.
      if [[ "$LOOP_WATCHDOG" == "1" ]]; then
        now="$(date +%s)"
        if (( now - last_loop_check >= LOOP_CHECK_INTERVAL )); then
          last_loop_check="$now"
          if game_loop_thread_alive "$child"; then
            loop_ok=1
            loop_failures=0
          else
            loop_ok=0
            loop_failures=$((loop_failures + 1))
            printf '[%s] loop watchdog: nro.cr.run not found (%s/%s), pid=%s\n' \
              "$(date '+%F %T')" "$loop_failures" "$LOOP_FAILS" "$child" >> "$SUP_LOG"
            trim_log "$SUP_LOG"
            if [[ "$loop_failures" -ge "$LOOP_FAILS" ]]; then
              printf '[%s] loop watchdog: game loop is gone; restarting GAME ONLY\n' \
                "$(date '+%F %T')" >> "$SUP_LOG"
              kill "$child" 2>/dev/null || true
              sleep 3
              kill -9 "$child" 2>/dev/null || true
              break
            fi
          fi
        fi
      fi

      # Freeze case seen on Elysian: Java + nro.cr.run can still exist while
      # the visible game is stuck. Only act when BOTH are true:
      #   1) the NRO loop was positively found in the latest thread check
      #   2) the game log has received no NEW output for STALL_TIMEOUT seconds
      # This avoids using a guessed network port and avoids killing a process
      # merely because one signal is missing.
      if [[ "$STALL_WATCHDOG" == "1" && "$loop_ok" == "1" ]]; then
        log_age="$(file_age_seconds "$GAME_LOG" 2>/dev/null || true)"
        if [[ -n "$log_age" && "$log_age" -ge "$STALL_TIMEOUT" ]]; then
          printf '[%s] freeze watchdog: nro.cr.run alive BUT game log unchanged for %ss; restarting GAME ONLY (pid=%s)\n' \
            "$(date '+%F %T')" "$log_age" "$child" >> "$SUP_LOG"
          kill "$child" 2>/dev/null || true
          sleep 3
          kill -9 "$child" 2>/dev/null || true
          break
        fi
      fi

      # IMPORTANT: do not restart a live game just because a guessed remote
      # NRO port is absent. Different client/server builds can use different
      # ports and the game itself has reconnect logic/settings. By default
      # the supervisor only restarts when the Java process actually exits.
      if [[ "$NETWORK_WATCHDOG" != "1" ]]; then
        continue
      fi

      elapsed=$(( $(date +%s) - started ))
      [[ "$elapsed" -lt "$HEALTH_GRACE" ]] && continue

      if game_connected; then
        failures=0
      else
        failures=$((failures + 1))
        printf '[%s] optional network watchdog: TCP :%s missing (%s/%s), pid=%s\n'           "$(date '+%F %T')" "$NRO_SERVER_PORT" "$failures" "$HEALTH_FAILS" "$child" >> "$SUP_LOG"
        trim_log "$SUP_LOG"
        if [[ "$failures" -ge "$HEALTH_FAILS" ]]; then
          echo "[$(date '+%F %T')] optional network watchdog: restarting game" >> "$SUP_LOG"
          kill "$child" 2>/dev/null || true
          sleep 3
          kill -9 "$child" 2>/dev/null || true
          break
        fi
      fi
    done

    wait "$child" 2>/dev/null || true
    rm -f "$GAME_PID"
    echo "[$(date '+%F %T')] game ended; restart in 2s" >> "$SUP_LOG"
    trim_log "$SUP_LOG"
    sleep 2
  done
}

start_game() {
  if [[ "$NETWORK_WATCHDOG" == "1" ]]; then
    echo "[GAME] network watchdog ENABLED on remote TCP :$NRO_SERVER_PORT"
  else
    echo "[GAME] network-port watchdog OFF; in-game reconnect remains in control"
  fi
  if [[ "$STALL_WATCHDOG" == "1" ]]; then
    echo "[GAME] freeze watchdog ENABLED: if nro.cr.run is alive + game log has no NEW output for ${STALL_TIMEOUT}s => restart GAME ONLY"
  else
    echo "[GAME] stall watchdog OFF"
  fi
  if [[ "$LOOP_WATCHDOG" == "1" ]]; then
    echo "[GAME] render-loop watchdog ENABLED: check nro.cr.run every ${LOOP_CHECK_INTERVAL}s, failures=${LOOP_FAILS}"
  else
    echo "[GAME] render-loop watchdog OFF"
  fi
  if pid_alive "$SUP_PID"; then
    echo "[GAME] supervisor already ON (pid $(cat "$SUP_PID"))"
    return 0
  fi

  : > "$SUP_LOG"
  nohup "$SELF" _game_loop >>"$SUP_LOG" 2>&1 &
  echo $! > "$SUP_PID"
  sleep 1
  if pid_alive "$SUP_PID"; then
    echo "[GAME] supervisor ON (pid $(cat "$SUP_PID"))"
  else
    echo "[GAME] supervisor failed"
    tail -n 80 "$SUP_LOG" 2>/dev/null || true
    return 1
  fi
}

restart_game_only() {
  local p cmd
  if ! pid_alive "$GAME_PID"; then
    echo "[GAME] no live game pid; supervisor will start it when needed"
    return 0
  fi

  p="$(cat "$GAME_PID" 2>/dev/null || true)"
  cmd="$(tr '\0' ' ' < "/proc/$p/cmdline" 2>/dev/null || true)"
  if [[ "$cmd" != *"org.microemu.app.Main"* ]]; then
    echo "[GAME] refusing to kill pid $p because it is not MicroEmulator"
    rm -f "$GAME_PID"
    return 1
  fi

  echo "[GAME] restarting game only (pid $p); VNC stays up"
  kill "$p" 2>/dev/null || true
}

stop_pidfile() {
  local f="$1" p i cmd=""
  if pid_alive "$f"; then
    p="$(cat "$f")"

    # A stale pidfile can point at an unrelated process after a container
    # restart. Only signal known NRO-owned processes.
    cmd="$(tr '\0' ' ' < "/proc/$p/cmdline" 2>/dev/null || true)"
    case "$f" in
      "$VNC_PID")
        [[ "$cmd" == *"Xtigervnc"* ]] || { rm -f "$f"; return 0; }
        ;;
      "$SUP_PID")
        [[ "$cmd" == *"nroctl.sh"*"_game_loop"* || "$cmd" == *"/elysian/nroctl.sh"*"_game_loop"* ]] || { rm -f "$f"; return 0; }
        ;;
      "$GAME_PID")
        [[ "$cmd" == *"org.microemu.app.Main"* ]] || { rm -f "$f"; return 0; }
        ;;
    esac

    kill "$p" 2>/dev/null || true
    for i in 1 2 3 4 5; do
      kill -0 "$p" 2>/dev/null || break
      sleep 0.4
    done
    kill -9 "$p" 2>/dev/null || true
  fi
  rm -f "$f"
}

stop_all() {
  echo "[NRO] stopping..."
  stop_pidfile "$SUP_PID"
  stop_pidfile "$GAME_PID"
  stop_pidfile "$VNC_PID"
  echo "[NRO] stopped"
}

status() {
  local vpid="" gpid="" spid=""
  vpid="$(find_vnc_pid || true)"
  gpid="$(find_game_pid || true)"
  if pid_alive "$SUP_PID"; then spid="$(cat "$SUP_PID")"; fi

  echo "================ NRO STATUS ================"
  [[ -n "$EMU_NAME" ]] && echo "Emulator:            $EMU_NAME" || echo "Emulator:            (not resolved)"
  [[ -n "$GAME_NAME" ]] && echo "Game:                $GAME_NAME" || echo "Game:                (not resolved)"
  [[ -n "$MIDLET_CLASS" ]] && echo "MIDlet:              $MIDLET_CLASS"
  [[ -n "$vpid" ]] && echo "[ON]  VNC process      pid=$vpid" || echo "[OFF] VNC process"
  port_listening && echo "[ON]  VNC port         :$VNC_PORT LISTEN" || echo "[OFF] VNC port         :$VNC_PORT"
  [[ -n "$spid" ]] && echo "[ON]  Game supervisor  pid=$spid" || echo "[OFF] Game supervisor"
  [[ -n "$gpid" ]] && echo "[ON]  Game Java        pid=$gpid" || echo "[OFF] Game Java"
  if game_connected; then
    echo "[INFO] Game network     observed TCP :$NRO_SERVER_PORT ESTABLISHED"
  else
    echo "[INFO] Game network     TCP :$NRO_SERVER_PORT not observed (not used for health)"
  fi
  [[ -s "$GAME" ]] && echo "[ON]  game.jar         $GAME" || echo "[OFF] game.jar"
  if [[ -f "$GAME_LOG" ]]; then
    log_age="$(file_age_seconds "$GAME_LOG" 2>/dev/null || true)"
    [[ -n "$log_age" ]] && echo "[INFO] Game log age     ${log_age}s"
  fi
  echo "State: $STATE"
  echo "============================================"
}

state_path_allowed() {
  case "$STATE" in
    "$ROOT/microemu-home/.microemulator")
      return 0
      ;;
    "$PROFILES_DIR"/*/.microemulator)
      return 0
      ;;
    *)
      return 1
      ;;
  esac
}

reset_state() {
  local emu_arg="${1:-}" game_arg="${2:-}" target

  # Stop the currently-running selection first so no process can write RMS
  # while its state directory is being removed.
  choose_runtime >/dev/null 2>&1 || true
  stop_all

  choose_runtime "$emu_arg" "$game_arg" || return 1
  target="$STATE"

  if ! state_path_allowed; then
    echo "[ERROR] Refusing to delete unexpected state path: $target" >&2
    return 1
  fi

  echo "[STATE] deleting: $target"
  rm -rf -- "$target"
  rm -f -- "$JAD"
  mkdir -p "$target/suite-null"
  echo "[STATE] reset complete for emulator=$EMU_NAME game=$GAME_NAME"
  echo "[STATE] run '$0 start' to launch with fresh state"
}

show_log() {
  echo "=== GAME ==="; tail -n 100 "$GAME_LOG" 2>/dev/null || true
  echo; echo "=== SUPERVISOR ==="; tail -n 100 "$SUP_LOG" 2>/dev/null || true
  echo; echo "=== VNC ==="; tail -n 100 "$VNC_LOG" 2>/dev/null || true
}

follow_log() {
  echo "[LOG] live follow started (GAME + SUPERVISOR + VNC)"
  echo "[LOG] use Elysian console command: log-stop"
  tail -n 40 -F "$GAME_LOG" "$SUP_LOG" "$VNC_LOG" 2>/dev/null
}

case "${1:-}" in
  list)
    list_runtime
    ;;
  start)
    if pid_alive "$SUP_PID" && { [[ -n "${2:-}" ]] || [[ -n "${3:-}" ]]; }; then
      echo "[ERROR] A game is already running; use restart <emulator> <game>"
      exit 1
    fi
    choose_runtime "${2:-}" "${3:-}" || exit 1
    prepare || exit 1
    start_vnc || exit 1
    start_game || exit 1
    sleep 1
    status
    ;;
  stop)
    stop_all
    ;;
  restart)
    # Validate the requested pair before stopping the current stack.
    choose_runtime "${2:-}" "${3:-}" || exit 1
    stop_all
    sleep 1
    prepare || exit 1
    start_vnc || exit 1
    start_game || exit 1
    sleep 1
    status
    ;;
  reset-state|delete-state)
    reset_state "${2:-}" "${3:-}" || exit 1
    ;;

  status)
    choose_runtime >/dev/null 2>&1 || true
    status
    ;;
  log)
    show_log
    ;;
  log-follow)
    follow_log
    ;;
  game-restart)
    restart_game_only
    ;;
  loop-check)
    choose_runtime >/dev/null 2>&1 || true
    if [[ "$LOOP_WATCHDOG" != "1" || -z "$LOOP_THREAD_PATTERN" ]]; then
      echo "[INFO] loop check unavailable for MIDlet ${MIDLET_CLASS:-unknown} (no verified thread pattern)"
    elif pid_alive "$GAME_PID"; then
      p="$(cat "$GAME_PID")"
      if game_loop_thread_alive "$p"; then
        echo "[ON] game loop pattern found in pid $p"
      else
        echo "[OFF] game loop pattern not found in pid $p"
      fi
    else
      echo "[OFF] game process not running"
    fi
    ;;
  _game_loop)
    choose_runtime || exit 2
    game_loop
    ;;
  *)
    echo "Usage: $0 {list|start [emulator game]|stop|restart [emulator game]|reset-state [emulator game]|status|log|log-follow|game-restart|loop-check}"
    exit 1
    ;;
esac
